# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acc07a8b9113f7328d7472a0fb33062924cdbf1c011373a5190b4848ab7bf735ff135fa4b9756f82e53888f394ccd48f59de683a76e453989424d17a21aec7c4

test:
  secret_key_base: bfa3a0a8459127666810f85515d7da37173416b50a34372a267a9224a9330893b1405e15e0cd16c1d612dbd114738c5f3d635c9f843c94010a8adb2f0248e0d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
